services:
  - type: web
    name: iptv-proxy
    env: node
    region: oregon        # Más cercano a Chile para menor latencia
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    nodeVersion: 20.19.2
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    autoDeploy: true
